//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OVR_Relay_application.OVRCServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OVRCard", Namespace="http://schemas.datacontract.org/2004/07/OVRCService")]
    [System.SerializableAttribute()]
    public partial class OVRCard : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float BField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float CaptionBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float CaptionGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float CaptionRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DurationMSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float GField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float RField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float TextBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float TextGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float TextRField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float B {
            get {
                return this.BField;
            }
            set {
                if ((this.BField.Equals(value) != true)) {
                    this.BField = value;
                    this.RaisePropertyChanged("B");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Caption {
            get {
                return this.CaptionField;
            }
            set {
                if ((object.ReferenceEquals(this.CaptionField, value) != true)) {
                    this.CaptionField = value;
                    this.RaisePropertyChanged("Caption");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float CaptionB {
            get {
                return this.CaptionBField;
            }
            set {
                if ((this.CaptionBField.Equals(value) != true)) {
                    this.CaptionBField = value;
                    this.RaisePropertyChanged("CaptionB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float CaptionG {
            get {
                return this.CaptionGField;
            }
            set {
                if ((this.CaptionGField.Equals(value) != true)) {
                    this.CaptionGField = value;
                    this.RaisePropertyChanged("CaptionG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float CaptionR {
            get {
                return this.CaptionRField;
            }
            set {
                if ((this.CaptionRField.Equals(value) != true)) {
                    this.CaptionRField = value;
                    this.RaisePropertyChanged("CaptionR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DurationMS {
            get {
                return this.DurationMSField;
            }
            set {
                if ((this.DurationMSField.Equals(value) != true)) {
                    this.DurationMSField = value;
                    this.RaisePropertyChanged("DurationMS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float G {
            get {
                return this.GField;
            }
            set {
                if ((this.GField.Equals(value) != true)) {
                    this.GField = value;
                    this.RaisePropertyChanged("G");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float R {
            get {
                return this.RField;
            }
            set {
                if ((this.RField.Equals(value) != true)) {
                    this.RField = value;
                    this.RaisePropertyChanged("R");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float TextB {
            get {
                return this.TextBField;
            }
            set {
                if ((this.TextBField.Equals(value) != true)) {
                    this.TextBField = value;
                    this.RaisePropertyChanged("TextB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float TextG {
            get {
                return this.TextGField;
            }
            set {
                if ((this.TextGField.Equals(value) != true)) {
                    this.TextGField = value;
                    this.RaisePropertyChanged("TextG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float TextR {
            get {
                return this.TextRField;
            }
            set {
                if ((this.TextRField.Equals(value) != true)) {
                    this.TextRField = value;
                    this.RaisePropertyChanged("TextR");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OVRCServiceReference.IOVRCardService")]
    public interface IOVRCardService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOVRCardService/Connect", ReplyAction="http://tempuri.org/IOVRCardService/ConnectResponse")]
        bool Connect();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOVRCardService/Connect", ReplyAction="http://tempuri.org/IOVRCardService/ConnectResponse")]
        System.Threading.Tasks.Task<bool> ConnectAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOVRCardService/PostCard", ReplyAction="http://tempuri.org/IOVRCardService/PostCardResponse")]
        void PostCard(OVR_Relay_application.OVRCServiceReference.OVRCard card);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOVRCardService/PostCard", ReplyAction="http://tempuri.org/IOVRCardService/PostCardResponse")]
        System.Threading.Tasks.Task PostCardAsync(OVR_Relay_application.OVRCServiceReference.OVRCard card);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOVRCardService/Disconnect", ReplyAction="http://tempuri.org/IOVRCardService/DisconnectResponse")]
        void Disconnect();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOVRCardService/Disconnect", ReplyAction="http://tempuri.org/IOVRCardService/DisconnectResponse")]
        System.Threading.Tasks.Task DisconnectAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOVRCardServiceChannel : OVR_Relay_application.OVRCServiceReference.IOVRCardService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OVRCardServiceClient : System.ServiceModel.ClientBase<OVR_Relay_application.OVRCServiceReference.IOVRCardService>, OVR_Relay_application.OVRCServiceReference.IOVRCardService {
        
        public OVRCardServiceClient() {
        }
        
        public OVRCardServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OVRCardServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OVRCardServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OVRCardServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Connect() {
            return base.Channel.Connect();
        }
        
        public System.Threading.Tasks.Task<bool> ConnectAsync() {
            return base.Channel.ConnectAsync();
        }
        
        public void PostCard(OVR_Relay_application.OVRCServiceReference.OVRCard card) {
            base.Channel.PostCard(card);
        }
        
        public System.Threading.Tasks.Task PostCardAsync(OVR_Relay_application.OVRCServiceReference.OVRCard card) {
            return base.Channel.PostCardAsync(card);
        }
        
        public void Disconnect() {
            base.Channel.Disconnect();
        }
        
        public System.Threading.Tasks.Task DisconnectAsync() {
            return base.Channel.DisconnectAsync();
        }
    }
}
